import Head from 'next/head'

function Signup() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Signup
    </div>
  )
}

export default Signup
